---
trust-domain: "translations"
task-priority: low
treeherder:
    group-names:
        "I": "Docker images"
        "Fetch": "Fetching tasks"
        "TL": "Toolchain tasks"
        "flores": "flores"
        "sacrebleu": "sacrebleu"
        "opus": "opus"
        "mtdata": "mtdata"
        "news-crawl": "news-crawl"

taskgraph:
    register: translations_taskgraph:register
    decision-parameters: "translations_taskgraph.parameters:get_decision_parameters"
    repositories:
        firefox_translations_training:
            name: "firefox-translations-training"

workers:
    aliases:
        b-linux:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
        b-linux-large:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
        # TODO: this should probably be b-linux...need to update ci-config
        t-linux-v100-gpu:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: '{alias}'
        t-linux-v100-gpu-4:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: '{alias}'
        images:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
        t-linux-large:
            provisioner: '{trust-domain}-t'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
