datasets:
  original: <dataset0> # Original parallel corpus

stages:
  - train

train:
  - original 1.0
  - until original inf # General training until marian early stops


modifiers:
- UpperCase: 0.07 # Apply randomly to 7% of sentences
- TitleCase: 0.05
- Typos: 0.05
- Noise: 0.0005
  min_word_length: 2 # Minimum word length for each word in the noisy sentence
  max_word_length: 5 # Maximum word length for each word in the noisy sentence
  max_words: 6 # Maximum number of words in each noisy sentence
- Tags: 0.05
  augment: 1
  custom_detok_src: <src>
  custom_detok_trg: <trg>
  vocab: <vocab>

seed: 1111
# parallel sentences + token alignments
num_fields: 3
